-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.profiles
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    deleted_at timestamp with time zone,
    user_id uuid,
    line_id character varying(40),
    name character varying(128) COLLATE pg_catalog."default" NOT NULL,
    nickname character varying(128) COLLATE pg_catalog."default" NOT NULL,
    url character varying(256) COLLATE pg_catalog."default",
    icon_image_url character varying(1024) COLLATE pg_catalog."default",
    role "public"."role" DEFAULT 'general'::"public"."role" NOT NULL,
    CONSTRAINT profiles_pkey PRIMARY KEY (id),
    CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.profiles
    OWNER to postgres;

ALTER TABLE IF EXISTS public.profiles
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.profiles TO anon;

GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO postgres;

GRANT ALL ON TABLE public.profiles TO service_role;

COMMENT ON TABLE public.profiles
    IS 'ユーザープロフィール';

COMMENT ON COLUMN public.profiles.id
    IS 'ユーザープロフィールID';

COMMENT ON COLUMN public.profiles.created_at
    IS '作成日時';

COMMENT ON COLUMN public.profiles.updated_at
    IS '更新日時';

COMMENT ON COLUMN public.profiles.deleted_at
    IS '削除日時';

COMMENT ON COLUMN public.profiles.user_id
    IS '認証ユーザーID';

COMMENT ON COLUMN public.profiles.line_id
    IS 'LINEユーザーID';

COMMENT ON COLUMN public.profiles.name
    IS 'ユーザー名';

COMMENT ON COLUMN public.profiles.nickname
    IS 'ユーザー表示名';

COMMENT ON COLUMN public.profiles.url
    IS '自由記述URL';

COMMENT ON COLUMN public.profiles.icon_image_url
    IS 'アイコン画像URL';

COMMENT ON COLUMN public.profiles.role
    IS '権限';

CREATE INDEX IF NOT EXISTS profiles_user_id_idx
    ON public.profiles USING btree
    (user_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE POLICY "Enable read access for all users"
    ON public.profiles
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (true);

CREATE TRIGGER handle_profiles_updated_at
    BEFORE UPDATE 
    ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION extensions.moddatetime('updated_at');
